#!/bin/bash

set -x

rm -rf _build

cmake -B _build -S . \
  -DCMAKE_INSTALL_PREFIX=_install \
  -DCMAKE_BUILD_TYPE=Release \
  -DOPENEXR_CXX_STANDARD=17 \
  -DBUILD_SHARED_LIBS=ON \
  -DOPENEXR_ENABLE_THREADING=ON \
  -DOPENEXR_INSTALL_PKG_CONFIG=ON \
  -DOPENEXR_INSTALL_DOCS=OFF \
  -DOPENEXR_BUILD_EXAMPLES=ON \
  -DOPENEXR_BUILD_TOOLS=ON \
  -DOPENEXR_FORCE_INTERNAL_IMATH=OFF \
  -DOPENEXR_FORCE_INTERNAL_DEFLATE=OFF \
  -DOPENEXR_FORCE_INTERNAL_OPENJPH=ON \
  -DBUILD_TESTING=ON \
  -DOPENEXR_RUN_FUZZ_TESTS=OFF \
  "-DCMAKE_C_FLAGS=-msse2 -mfpmath=sse" \
  "-DCMAKE_CXX_FLAGS=-msse2 -mfpmath=sse" \
  -DCMAKE_VERBOSE_MAKEFILE=ON

cmake --version

cmake --build _build --target install --config Release

find . -ls
