# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) Contributors to the OpenEXR Project.
#

name: CI-examples

on:
  push:
    paths:
      - '**'
      - '!**.md'
      - '!website/**'
      - 'website/src/**'
      - '!bazel/**'
      - '!src/wrappers/**'
      - '!share/ci/**'
      - '!.github/workflows/**'
      - '.github/workflows/ci_examples.yml'
  pull_request:
    paths:
      - '**'
      - '!**.md'
      - '!website/**'
      - 'website/src/**'
      - '!bazel/**'
      - '!src/wrappers/**'
      - '!share/ci/**'
      - '!.github/workflows/**'
      - '.github/workflows/ci_examples.yml'

permissions:
  contents: read

jobs:

  linux:
    name: 'Website examples'
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - name: Configure
        shell: bash
        run: |
          set -x
          BUILD_DIR=$GITHUB_WORKSPACE/_build
          echo BUILD_DIR="$BUILD_DIR" >> $GITHUB_ENV

          INSTALL_DIR=$GITHUB_WORKSPACE/_install
          echo INSTALL_DIR="$INSTALL_DIR" >> $GITHUB_ENV

          cmake -B $BUILD_DIR -S $GITHUB_WORKSPACE \
                -DCMAKE_INSTALL_PREFIX=$INSTALL_DIR \
                -DCMAKE_VERBOSE_MAKEFILE:BOOL='ON' \
                -DCMAKE_CXX_FLAGS=" -fsanitize=undefined,address " \
                -DCMAKE_C_FLAGS=" -fsanitize=undefined,address " 

      - name: Build
        shell: bash
        run: |
          set -x
          cmake --build $BUILD_DIR --target install --config Release

      - name: Website examples
        run: |
          set -x
          EXRWRITER_BUILD_DIR=$BUILD_DIR.exrwritre
          cmake -S website/src/exrwriter -B $EXRWRITER_BUILD_DIR \
                -DCMAKE_PREFIX_PATH=$INSTALL_DIR \
                -DCMAKE_BUILD_TYPE=Release \
                -DCMAKE_CXX_FLAGS=" -fsanitize=undefined,address " \
                -DCMAKE_C_FLAGS=" -fsanitize=undefined,address " 

          cmake --build $EXRWRITER_BUILD_DIR --config Release

          $EXRWRITER_BUILD_DIR/exrwriter
          EXRINFO=$INSTALL_DIR/bin/exrinfo
          if [ -x "$EXRINFO" ]; then
              "$EXRINFO" hello.exr
          fi
        shell: bash
