# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) Contributors to the OpenEXR Project.
#
# GitHub Actions workflow file
# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: CI

# Run on all changes except:
# - doc file changes
# - changes to the website, *except* for "website/src", since that
#   code needs validation.  The website has a separate workflow
# - changes to the bazel config, since it has its own workflow
# - changes to the python bindings
# - changes to workflows other than this one

on:
  push:
    paths:
      - '**'
      - '!**.md'
      - '!website/**'
      - 'website/src/**'
      - '!bazel/**'
      - '!src/wrappers/**'
      - '!.github/workflows/**'
      - '.github/workflows/ci_workflow.yml'
      - '.github/workflows/ci_steps.yml'
  pull_request:
    paths:
      - '**'
      - '!**.md'
      - '!website/**'
      - 'website/src/**'
      - '!bazel/**'
      - '!src/wrappers/**'
      - '!.github/workflows/**'
      - '.github/workflows/ci_workflow.yml'
      - '.github/workflows/ci_steps.yml'

permissions:
  contents: read

jobs:
  linux:
    name: 'Linux ${{ matrix.build}}: ${{ matrix.vfx-cy }}
       ${{ matrix.compiler-desc }}
       C++${{ matrix.cxx-standard }}
       ${{ matrix.build-type }}
       ${{ matrix.label }}'
    uses: ./.github/workflows/ci_steps.yml
    with:
      os: ubuntu-latest
      container: 'aswf/ci-openexr:${{ matrix.vfx-cy }}'
      vfx-cy: ${{ matrix.vfx-cy }}
      compiler-desc: ${{ matrix.compiler-desc }}
      cxx-compiler: ${{ matrix.cxx-compiler }}
      cc-compiler: ${{ matrix.cc-compiler }}
      cxx-standard: ${{ matrix.cxx-standard }}
      build-type: ${{ matrix.build-type }}
      BUILD_SHARED_LIBS: ${{ matrix.BUILD_SHARED_LIBS }}
      OPENEXR_ENABLE_THREADING: ${{ matrix.OPENEXR_ENABLE_THREADING }}
      OPENEXR_INSTALL_PKG_CONFIG: ${{ matrix.OPENEXR_INSTALL_PKG_CONFIG }}
      OPENEXR_INSTALL_DOCS: ${{ matrix.OPENEXR_INSTALL_DOCS }}
      OPENEXR_BUILD_EXAMPLES: ${{ matrix.OPENEXR_BUILD_EXAMPLES }}
      OPENEXR_BUILD_TOOLS: ${{ matrix.OPENEXR_BUILD_TOOLS }}
      OPENEXR_BUILD_PYTHON: ${{ matrix.OPENEXR_BUILD_PYTHON }}
      OPENEXR_FORCE_INTERNAL_IMATH: ${{ matrix.OPENEXR_FORCE_INTERNAL_IMATH }}
      OPENEXR_FORCE_INTERNAL_DEFLATE: ${{ matrix.OPENEXR_FORCE_INTERNAL_DEFLATE }}
      BUILD_TESTING: ${{ matrix.BUILD_TESTING }}
    strategy:
      matrix:
        build: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
        include:

          - vfx-cy: 2024
          - compiler-desc: gcc11.2.1
          - cxx-compiler: g++
          - cc-compiler: gcc
          - cxx-standard: 17
          - build-type: Release
          - BUILD_SHARED_LIBS: 'ON'
          - OPENEXR_ENABLE_THREADING: 'ON'
          - OPENEXR_INSTALL_PKG_CONFIG: 'ON'
          - OPENEXR_INSTALL_DOCS: 'OFF'
          - OPENEXR_BUILD_EXAMPLES: 'ON'
          - OPENEXR_BUILD_TOOLS: 'ON'
          - OPENEXR_BUILD_PYTHON: 'OFF'
          - OPENEXR_FORCE_INTERNAL_IMATH: 'OFF'
          - OPENEXR_FORCE_INTERNAL_DEFLATE: 'OFF'
          - BUILD_TESTING: 'OFF'

          - build: 1
            build-type: Debug

          - build: 2

          - build: 3
            label: Static
            BUILD_SHARED_LIBS: 'OFF'

          - build: 4
            label: threads=OFF
            OPENEXR_ENABLE_THREADING: 'OFF'

          - build: 5
            label: pkgconfig=OFF, examples=OFF, tools=OFF, docs=OFF, internal deflate
            OPENEXR_INSTALL_PKG_CONFIG: 'OFF'
            OPENEXR_INSTALL_DOCS: 'OFF'
            OPENEXR_BUILD_EXAMPLES: 'OFF'
            OPENEXR_BUILD_TOOLS: 'OFF'
            OPENEXR_FORCE_INTERNAL_IMATH: 'ON'
            OPENEXR_FORCE_INTERNAL_DEFLATE: 'ON'
            BUILD_TESTING: 'OFF'

          - build: 6
            label: clang15.0
            compiler-desc: clang15.0
            cxx-compiler: clang++
            cc-compiler: clang

          - build: 7
            label: clang14.0
            compiler-desc: clang14.0
            cxx-compiler: clang++
            cc-compiler: clang

          - build: 8
            label: vfx2023
            vfx-cy: 2023

          - build: 9
            label: vfx2022
            vfx-cy: 2022
            compiler-desc: gcc9.3.1

          - build: 10
            label: vfx2021
            vfx-cy: 2021
            compiler-desc: gcc9.3.1

  macOS:
    name: 'macOS ${{ matrix.build}}: ${{ matrix.os }} ${{ matrix.vfx-cy }}
       ${{ matrix.compiler-desc }}
       C++${{ matrix.cxx-standard }}
       ${{ matrix.build-type }}
       ${{ matrix.label }}'
    uses: ./.github/workflows/ci_steps.yml
    with:
      os: ${{ matrix.os }}
      vfx-cy: ${{ matrix.vfx-cy }}
      compiler-desc: ${{ matrix.compiler-desc }}
      cxx-compiler: ${{ matrix.cxx-compiler }}
      cc-compiler: ${{ matrix.cc-compiler }}
      cxx-standard: ${{ matrix.cxx-standard }}
      build-type: ${{ matrix.build-type }}
      BUILD_SHARED_LIBS: ${{ matrix.BUILD_SHARED_LIBS }}
      OPENEXR_ENABLE_THREADING: ${{ matrix.OPENEXR_ENABLE_THREADING }}
      OPENEXR_INSTALL_PKG_CONFIG: ${{ matrix.OPENEXR_INSTALL_PKG_CONFIG }}
      OPENEXR_INSTALL_DOCS: ${{ matrix.OPENEXR_INSTALL_DOCS }}
      OPENEXR_BUILD_EXAMPLES: ${{ matrix.OPENEXR_BUILD_EXAMPLES }}
      OPENEXR_BUILD_TOOLS: ${{ matrix.OPENEXR_BUILD_TOOLS }}
      OPENEXR_BUILD_PYTHON: ${{ matrix.OPENEXR_BUILD_PYTHON }}
      OPENEXR_FORCE_INTERNAL_IMATH: ${{ matrix.OPENEXR_FORCE_INTERNAL_IMATH }}
      OPENEXR_FORCE_INTERNAL_DEFLATE: ${{ matrix.OPENEXR_FORCE_INTERNAL_DEFLATE }}
      BUILD_TESTING: ${{ matrix.BUILD_TESTING }}
    strategy:
      matrix:
        build: [1, 2, 3, 4, 5]
        include:
          # defaults settings. These are inherited for each build below.
          - vfx-cy: 2024
          - os: macos-12
          - compiler-desc: AppleClang11.0
          - cxx-standard: 17
          - build-type: Release
          - BUILD_SHARED_LIBS: 'ON'
          - OPENEXR_ENABLE_THREADING: 'ON'
          - OPENEXR_INSTALL_PKG_CONFIG: 'ON'
          - OPENEXR_INSTALL_DOCS: 'ON'
          - OPENEXR_BUILD_EXAMPLES: 'ON'
          - OPENEXR_BUILD_TOOLS: 'ON'
          - OPENEXR_BUILD_PYTHON: 'OFF'
          - OPENEXR_FORCE_INTERNAL_IMATH: 'OFF'
          - OPENEXR_FORCE_INTERNAL_DEFLATE: 'OFF'
          - BUILD_TESTING: 'OFF'

          - build: 1
            build-type: Debug

          - build: 2

          - build: 3
            label: Static
            BUILD_SHARED_LIBS: 'OFF'

          - build: 4
            label: threads=OFF
            OPENEXR_ENABLE_THREADING: 'OFF'

          - build: 5
            label: pkgconfig=OFF, examples=OFF, tools=OFF, docs=OFF, internal imath+deflate
            OPENEXR_INSTALL_PKG_CONFIG: 'OFF'
            OPENEXR_INSTALL_DOCS: 'OFF'
            OPENEXR_BUILD_EXAMPLES: 'OFF'
            OPENEXR_BUILD_TOOLS: 'OFF'
            OPENEXR_FORCE_INTERNAL_IMATH: 'ON'
            OPENEXR_FORCE_INTERNAL_DEFLATE: 'ON'
            BUILD_TESTING: 'OFF'

  windows:
    name: 'Windows ${{ matrix.build}}: ${{ matrix.os }} ${{ matrix.vfx-cy }}
       ${{ matrix.compiler-desc }}
       C++${{ matrix.cxx-standard }}
       ${{ matrix.build-type }}
       ${{ matrix.label }}'
    uses: ./.github/workflows/ci_steps.yml
    with:
      os: windows-2022
      vfx-cy: ${{ matrix.vfx-cy }}
      compiler-desc: ${{ matrix.compiler-desc }}
      cxx-compiler: ${{ matrix.cxx-compiler }}
      cc-compiler: ${{ matrix.cc-compiler }}
      cxx-standard: ${{ matrix.cxx-standard }}
      build-type: ${{ matrix.build-type }}
      BUILD_SHARED_LIBS: ${{ matrix.BUILD_SHARED_LIBS }}
      OPENEXR_ENABLE_THREADING: ${{ matrix.OPENEXR_ENABLE_THREADING }}
      OPENEXR_INSTALL_PKG_CONFIG: ${{ matrix.OPENEXR_INSTALL_PKG_CONFIG }}
      OPENEXR_INSTALL_DOCS: ${{ matrix.OPENEXR_INSTALL_DOCS }}
      OPENEXR_BUILD_EXAMPLES: ${{ matrix.OPENEXR_BUILD_EXAMPLES }}
      OPENEXR_BUILD_TOOLS: ${{ matrix.OPENEXR_BUILD_TOOLS }}
      OPENEXR_BUILD_PYTHON: ${{ matrix.OPENEXR_BUILD_PYTHON }}
      OPENEXR_FORCE_INTERNAL_IMATH: ${{ matrix.OPENEXR_FORCE_INTERNAL_IMATH }}
      OPENEXR_FORCE_INTERNAL_DEFLATE: ${{ matrix.OPENEXR_FORCE_INTERNAL_DEFLATE }}
      BUILD_TESTING: ${{ matrix.BUILD_TESTING }}
    strategy:
      matrix:
        build: [1]
        include:
          # defaults settings. These are inherited for each build below.
          - vfx-cy: 2023
          - os: windows-2022
          - compiler-desc: msvc17.5
          - cxx-standard: 17
          - build-type: Release
          - BUILD_SHARED_LIBS: 'ON'
          - OPENEXR_ENABLE_THREADING: 'ON'
          - OPENEXR_INSTALL_PKG_CONFIG: 'ON'
          - OPENEXR_INSTALL_DOCS: 'OFF'
          - OPENEXR_BUILD_EXAMPLES: 'ON'
          - OPENEXR_BUILD_TOOLS: 'ON'
          - OPENEXR_BUILD_PYTHON: 'OFF'
          - OPENEXR_FORCE_INTERNAL_IMATH: 'OFF'
          - OPENEXR_FORCE_INTERNAL_DEFLATE: 'OFF'
          - BUILD_TESTING: 'OFF'

          - build: 1
            build-type: Debug

