# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) Contributors to the OpenEXR Project.

name: Publish Python Wheels to test.pypi

on:
  # Publish python wheels to test.pypi when a release branch is tagged
  # as an "-rc" release candidate, e.g. v3.2.4-rc, v3.2.4-rc2, etc.
  push:
    branches:
      - RB-3.*
    tags:
      - v3.*.*-rc*
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build_wheels:
    name: Python Wheels - ${{ matrix.os }} 
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
#        os: [ubuntu-latest, macos-latest, windows-latest]

    environment:
      name: testpypi
      url: https://test.pypi.org/p/openexr

    permissions:
      id-token: write
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Python 
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Build wheel
        uses: pypa/cibuildwheel@v2.16
        env:
          CIBW_BUILD: cp312-*
          CIBW_ARCHS_LINUX: x86_64 
          CIBW_ARCHS_MACOS: x86_64 arm64 universal2
          # Skip python 3.6 since scikit-build-core requires 3.7+
          # Skip 32-bit wheels builds on Windows
          # Also skip the PyPy builds, since they fail the unit tests
          CIBW_SKIP: cp36-* *-win32 *_i686 pp* 
          CIBW_TEST_SKIP: "*-macosx_universal2:arm64"

      - name: Upload artifact
        uses: actions/upload-artifact@v4.0.0
        with:
          path: wheelhouse/*.whl

      - name: Publish distribution 📦 to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
  

