# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) Contributors to the OpenEXR Project.

name: Python Wheels

on:

  # Run on all changes (PR and push) to the python binding
  # source/configuration files, except on the release branches, which
  # have their own workflow, which also publish to pypi/test.pypi.
  # Note that changes to the core libraries will *not*
  # trigger building the wheels. However, the main ci workflow does
  # build and test the bindings (for a single python version on a
  # single arch)

  push:
    branches-ignore:
      - RB-*
    paths:
      - 'cmake/**'
      - 'src/lib/**'
      - 'src/wrappers/python/**'
      - 'pyproject.toml'
      - '!share/ci/install_manifest/**'
      - '!.github/workflows/**'
      - '.github/workflows/python-wheels.yml'
  pull_request:
    branches-ignore:
      - RB-*
    paths:
      - 'cmake/**'
      - 'src/lib/**'
      - 'src/wrappers/python/**'
      - 'pyproject.toml'
      - '!share/ci/install_manifest/**'
      - '!.github/workflows/**'
      - '.github/workflows/python-wheels.yml'

permissions:
  contents: read

jobs:

  build_sdist:
    name: Build sdist
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Install Python
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
        with:
          python-version: '3.x'

      - name: Create sdist
        env:
          CMAKE_MINIMUM_VERSION: 3.15
        run: pipx run build --sdist . --outdir /tmp/wheelhouse

      - name: Upload sdist
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: sdist
          path: /tmp/wheelhouse/*.tar.gz

  build_wheels:
    name: Python Wheels - ${{ matrix.os }}-${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    needs: build_sdist
    strategy:
      matrix:
        include:
          - os: ubuntu-24.04
            arch: x64
          - os: ubuntu-24.04-arm
            arch: arm64
          - os: macos-13
            arch: x64
          - os: macos-latest
            arch: arm64
          - os: windows-latest
            arch: x64

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Install Python
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
        with:
          python-version: '3.x'

      - name: Download sdist
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4
        with:
          name: sdist
          path: wheelhouse

      - name: Build wheel
        uses: pypa/cibuildwheel@faf86a6ed7efa889faf6996aa23820831055001a # v2.23
        env:
          CIBW_ARCHS_MACOS: x86_64 arm64 universal2
          # Build Python 3.8 through 3.13
          # Skip 32-bit wheels builds on Windows
          # Also skip the PyPy builds, since they fail the unit tests
          CIBW_BUILD: "cp38-* cp39-* cp310-* cp311-* cp312-* cp313-*"
          CIBW_SKIP: "*-win32 *_i686"
          CIBW_TEST_SKIP: "*-macosx*arm64"
          OPENEXR_TEST_IMAGE_REPO: "https://raw.githubusercontent.com/AcademySoftwareFoundation/openexr-images/main"

      - name: Upload artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: wheels-${{ matrix.os }}-${{ matrix.arch }}
          path: |
            ./wheelhouse/*.whl
            ./wheelhouse/*.tar.gz

