# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) Contributors to the OpenEXR Project.

name: Python Wheels

on:

  # Run on all changes to the python binding source/configuration
  # files, except on the release branches, which have their own
  # workflow. Note that changes to the core libraries will *not*
  # trigger building the wheels, although the main ci workflow does
  # build and test the bindings (for the latest python version and on
  # a single arch)

  push:
    branches-ignore:
      - RB-*
    paths:
      - 'src/wrappers/python/**'
      - 'pyproject.toml'
      - '.github/workflows/python-wheels.yml'
  pull_request:
    branches-ignore:
      - RB-*
    paths:
      - 'src/wrappers/python/**'
      - 'pyproject.toml'
      - '.github/workflows/python-wheels.yml'

permissions:
  contents: read

jobs:
  build_wheels:
    name: Python Wheels - ${{ matrix.os }} 
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
       - name: Install Node
         uses: actions/setup-node@v3
         with:
            node-version: '20'

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Python 
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Build wheel
        uses: pypa/cibuildwheel@v2.16
        env:
#          CIBW_ARCHS_LINUX: x86_64 
          CIBW_ARCHS_MACOS: x86_64 arm64 universal2
          # Skip python 3.6 since scikit-build-core requires 3.7+
          # Skip 32-bit wheels builds on Windows
          # Also skip the PyPy builds, since they fail the unit tests
          CIBW_SKIP: cp36-* *-win32 *_i686 pp* 
          CIBW_TEST_SKIP: "*_arm64"

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
#          name: wheel-${{ matrix.os }}
          path: wheelhouse/*.whl

