# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) Contributors to the OpenEXR Project.

name: Publish python distribution 📦 to TestPyPI

on:

  # Publish python wheels to test.pypi when a release candidate is tagged,
  # e.g. v3.4.5-rc, v3.4.5-rc6, etc.

  push:
    tags:
      - v3.[0-9]+.[0-9]+-rc*
  workflow_dispatch:

permissions:
  contents: read

jobs:

  build_sdist:
    name: Build sdist
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Install Python
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
        with:
          python-version: '3.x'

      - name: Create sdist
        env:
          OPENEXR_RELEASE_CANDIDATE_TAG: ${{ github.ref_name }}
          CMAKE_MINIMUM_VERSION: 3.15
        run: pipx run build --sdist . --outdir /tmp/wheelhouse

      - name: Upload sdist
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: sdist
          path: /tmp/wheelhouse/*.tar.gz

  build_wheels:
    name: Python Wheels - ${{ matrix.os }}-${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-24.04
            arch: x64
          - os: ubuntu-24.04-arm
            arch: arm64
          - os: macos-13
            arch: x64
          - os: macos-latest
            arch: arm64
          - os: windows-latest
            arch: x64

    environment:
      name: testpypi
      url: https://test.pypi.org/p/openexr

    permissions:
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Install Python
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
        with:
          python-version: '3.x'

      - name: Download sdist
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          name: sdist
          path: wheelhouse

      - name: Build wheel
        uses: pypa/cibuildwheel@faf86a6ed7efa889faf6996aa23820831055001a # v2.23
        env:
          MACOSX_DEPLOYMENT_TARGET: 10.15
          CIBW_ARCHS_MACOS: x86_64 arm64 universal2
          # Build Python 3.8 through 3.13
          # Skip 32-bit wheels builds on Windows
          # Also skip the PyPy builds, since they fail the unit tests
          CIBW_BUILD: "cp38-* cp39-* cp310-* cp311-* cp312-* cp313-*"
          CIBW_SKIP: "*-win32 *_i686"
          CIBW_TEST_SKIP: "*-macosx*arm64"
          CIBW_ENVIRONMENT: OPENEXR_RELEASE_CANDIDATE_TAG="${{ github.ref_name }}"
          OPENEXR_TEST_IMAGE_REPO: "https://raw.githubusercontent.com/AcademySoftwareFoundation/openexr-images/main"

      - name: Upload artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: wheels-${{ matrix.os }}-${{ matrix.arch }}
          path: |
            ./wheelhouse/*.whl
            ./wheelhouse/*.tar.gz

  publish-to-testpypi:
    name: Publish Python 🐍 distribution 📦 to TestPyPI
    needs:
    - build
    runs-on: ubuntu-24.04

    environment:
      name: testpypi
      url: https://test.pypi.org/p/openexr

    permissions:
      id-token: write

    steps:

    - name: Download ubuntu-24.04-x64 artifacts
      uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
      with:
        name: wheels-ubuntu-24.04-x64
        path: dist

    - name: Download ubuntu-24.04-arm-arm64 artifacts
      uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
      with:
        name: wheels-ubuntu-24.04-arm-arm64
        path: dist

    - name: Download macos-13-x64 artifacts
      uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
      with:
        name: wheels-macos-13-x64
        path: dist

    - name: Download macos-24.04-arm64
      uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
      with:
        name: wheels-macos-24.04-arm64
        path: dist

    - name: Download windows-24.04-x64 artifacts
      uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
      with:
        name: wheels-windows-24.04-x64
        path: dist

    - name: Publish distribution 📦 to TestPyPI
      uses: pypa/gh-action-pypi-publish@67339c736fd9354cd4f8cb0b744f2b82a74b5c70 # v1.12.3
      with:
        repository-url: https://test.pypi.org/legacy/
