# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) Contributors to the OpenEXR Project.

name: Python Wheels

on:
  push:
    branches-ignore:
      - RB-2.*
    tags-ignore:
      - v1.*
      - v2.*
    paths:
      - '**'
      - '!**.md'
      - '!website/**'
      - '!bazel/**'
  pull_request:
    branches-ignore:
      - RB-2.*
    tags-ignore:
      - v1.*
      - v2.*
    paths:
      - '**'
      - '!**.md'
      - '!website/**'
      - '!bazel/**'

permissions:
  contents: read

jobs:
  build_wheels:
    name: Build Wheels on ${{ matrix.os }} for Python 3.${{ matrix.python-minor }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        python-minor: ['7', '8, '9', '10', '11', '12']
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Python 3.${{ matrix.python-minor }}
        uses: actions/setup-python@v4
        with:
          python-version: 3.${{ matrix.python-minor }}

      - name: Build wheel
        uses: pypa/cibuildwheel@v2.16
        env:
          CIBW_ARCHS_MACOS: x86_64 arm64 
          # Skip 32-bit wheels builds on Windows.
          # Also skip the PyPy builds, since they fail the unittests
          CIBW_SKIP: "*-win32 *_i686 pp*"

#          CIBW_BUILD: 'cp3${{ matrix.python-minor }}-*'
#          CIBW_ARCHS_MACOS: universal2
#          CIBW_ARCHS_WINDOWS: auto ARM64

      - name: Verify clean directory
        run: git diff --exit-code
        shell: bash

      - name: Updload artifact
        uses: actions/upload-artifact@v3
        with:
          path: wheelhouse/*.whl



