# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) Contributors to the OpenEXR Project.

name: Python Wheels

on:
  release:
    # Release triggers a build followed by a publish
    types: [published]
  push:
#    branches:
#      # Run whenever any change is pushed to a release branch
#      - RB-3.*
    paths:
      # Run on all changes to the python binding source/configuration files, regardless of branch
      - 'src/wrappers/python/**'
      - 'pyproject.toml'
      - '.github/workflows/python-wheels.yml'
  pull_request:
    paths:
      # Run on all changes to the python binding source/configuration files, regardless of branch
      - 'src/wrappers/python/**'
      - 'pyproject.toml'
      - '.github/workflows/python-wheels.yml'

permissions:
  contents: read

jobs:
  build_wheels:
    name: Python Wheels - ${{ matrix.os }} 
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
#        os: [ubuntu-latest, macos-latest, windows-latest]

    runs:
      using: 'node20'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Python 
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Build wheel
        uses: pypa/cibuildwheel@v2.16
        env:
          CIBW_ARCHS_LINUX: x86_64 
          CIBW_ARCHS_MACOS: x86_64 arm64 universal2
          # Skip python 3.6 since scikit-build-core requires 3.7+
          # Skip 32-bit wheels builds on Windows
          # Also skip the PyPy builds, since they fail the unit tests
          CIBW_SKIP: cp36-* *-win32 *_i686 pp* 
          CIBW_TEST_SKIP: "*_arm64"

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          path: wheelhouse/*.whl

      - name: Publish Wheel
        # Only publish the wheel to pypa on release
        if: github.event_name == 'release'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}

