# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) Contributors to the OpenEXR Project.

name: Python Wheels

on:
  push:
    branches-ignore:
      - RB-2.*
    tags-ignore:
      - v1.*
      - v2.*
    paths:
      - '**'
      - '!**.md'
      - '!website/**'
      - '!bazel/**'
  pull_request:
    branches-ignore:
      - RB-2.*
    tags-ignore:
      - v1.*
      - v2.*
    paths:
      - '**'
      - '!**.md'
      - '!website/**'
      - '!bazel/**'

permissions:
  contents: read

jobs:
  build_wheels:
    name: Python Wheels - ${{ matrix.os }} 
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
#        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Python 
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Build wheel
        uses: pypa/cibuildwheel@v2.16
        env:
          # Skip python 3.6 since scikit-build-core requires 3.7+
          # Skip 32-bit wheels builds on Windows
          # Also skip the PyPy builds, since they fail the unit tests
          CIBW_SKIP: cp36-* cp37-* cp38-* cp39-* cp310-* cp312-* *-win32 *_i686 pp* 

      - name: Updload artifact
        uses: actions/upload-artifact@v3
        with:
          path: wheelhouse/*.whl
