# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) Contributors to the OpenEXR Project.

name: Python Wheels

on:
  push:
    branches-ignore:
      - RB-2.*
    tags-ignore:
      - v1.*
      - v2.*
    paths:
      - '**'
      - '!**.md'
      - '!website/**'
      - '!bazel/**'
  pull_request:
    branches-ignore:
      - RB-2.*
    tags-ignore:
      - v1.*
      - v2.*
    paths:
      - '**'
      - '!**.md'
      - '!website/**'
      - '!bazel/**'

permissions:
  contents: read

# manylinux: aarch6 x86_64 # skip: i686 ppc64le x390x
# musllinux: aarch6 x86_64 # skip: i686 ppc64le x390x
# macos: arm64 universal2 x86_64
# win: amd64 arm64

# arch: [aarch6 amd64 arm64 universal2 x86_64] 

jobs:
  build_wheels_linux:
    name: Build Python Wheel on ${{ matrix.os }} 
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        arch: [x86_64] 
#        arch: [aarch6 x86_64] 
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Python 
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Create build directories
        run: |
          mkdir _install
          mkdir _build

      - name: Configure OpenEXR libraries
        run: |
          cmake .. \
                -DCMAKE_INSTALL_PREFIX=../_install \
                -DCMAKE_BUILD_TYPE=Release \
                -DBUILD_SHARED_LIBS='OFF' \
                -DOPENEXR_INSTALL_TOOLS='OFF' \
                -DOPENEXR_INSTALL_DOCS='OFF'
        working-directory: _build

      - name: Build OpenEXR libraries
        run: |
          cmake --build . \
                --target install \
                --config Release
        working-directory: _build

      - name: Build wheel
        uses: pypa/cibuildwheel@v2.16
        env:
          CIBW_SKIP: cp36-* cp37-* cp38-* cp39-* cp310-* *-win32 *_i686 pp* 

      - name: Updload artifact
        uses: actions/upload-artifact@v3
        with:
          path: wheelhouse/*.whl
