name: Test Action

on:
  push:
    paths:
      - '**'

jobs:

  test:

    name: Test
    runs-on: ubuntu-latest

    env:
       TAG: v3.2.4
       
    steps:

      - name: Set Version
        run: echo OPENEXR_PREFIX=openexr-${TAG//v} >> $GITHUB_ENV
        shell: bash
        
      - name: Create archive
        run: git archive --format=tar.gz -o ${OPENEXR_PREFIX}.tar.gz --prefix ${OPENEXR_PREFIX} ${TAG}

      - name: Validate archive
        run: tar tvf openexr-3.2.4.tar.gz